/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppointmentRequest {
  'urgencyLevel' : UrgencyLevel,
  'fullName' : string,
  'submittedAt' : bigint,
  'submittedBy' : [] | [Principal],
  'churchOrOrganization' : [] | [string],
  'preferredDate' : bigint,
  'preferredTime' : bigint,
  'consentGiven' : boolean,
  'details' : string,
  'emailAddress' : string,
  'phoneNumber' : string,
  'requestType' : RequestType,
  'leaderRequested' : string,
}
export interface PrayerRequest {
  'id' : bigint,
  'isEmergency' : boolean,
  'status' : RequestStatus,
  'urgencyLevel' : UrgencyLevel,
  'prayerRequest' : string,
  'fullName' : string,
  'submittedAt' : bigint,
  'submittedBy' : [] | [Principal],
  'emailAddress' : string,
  'phoneNumber' : [] | [string],
}
export type RequestStatus = { 'resolved' : null } |
  { 'open' : null } |
  { 'inProgress' : null };
export type RequestType = { 'other' : null } |
  { 'speakingEngagement' : null } |
  { 'mediaInterview' : null } |
  { 'prayerCounseling' : null } |
  { 'consultation' : null };
export type UrgencyLevel = { 'emergency' : null } |
  { 'routine' : null } |
  { 'timeSensitive' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllPrayerRequests' : ActorMethod<[], Array<PrayerRequest>>,
  'getAllRequests' : ActorMethod<[], Array<AppointmentRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmergencyPrayerRequests' : ActorMethod<[], Array<PrayerRequest>>,
  'getPrayerRequest' : ActorMethod<[bigint], [] | [PrayerRequest]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAppointmentRequest' : ActorMethod<[AppointmentRequest], undefined>,
  'submitEmergencyPrayer' : ActorMethod<[string, string, string], bigint>,
  'submitPrayerRequest' : ActorMethod<
    [string, string, [] | [string], string, UrgencyLevel],
    bigint
  >,
  'updatePrayerRequestStatus' : ActorMethod<[bigint, RequestStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];