/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UrgencyLevel = IDL.Variant({
  'emergency' : IDL.Null,
  'routine' : IDL.Null,
  'timeSensitive' : IDL.Null,
});
export const RequestType = IDL.Variant({
  'other' : IDL.Null,
  'speakingEngagement' : IDL.Null,
  'mediaInterview' : IDL.Null,
  'prayerCounseling' : IDL.Null,
  'consultation' : IDL.Null,
});
export const AppointmentRequest = IDL.Record({
  'urgencyLevel' : UrgencyLevel,
  'fullName' : IDL.Text,
  'submittedAt' : IDL.Int,
  'submittedBy' : IDL.Opt(IDL.Principal),
  'churchOrOrganization' : IDL.Opt(IDL.Text),
  'preferredDate' : IDL.Int,
  'preferredTime' : IDL.Nat,
  'consentGiven' : IDL.Bool,
  'details' : IDL.Text,
  'emailAddress' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'requestType' : RequestType,
  'leaderRequested' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllRequests' : IDL.Func([], [IDL.Vec(AppointmentRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAppointmentRequest' : IDL.Func([AppointmentRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UrgencyLevel = IDL.Variant({
    'emergency' : IDL.Null,
    'routine' : IDL.Null,
    'timeSensitive' : IDL.Null,
  });
  const RequestType = IDL.Variant({
    'other' : IDL.Null,
    'speakingEngagement' : IDL.Null,
    'mediaInterview' : IDL.Null,
    'prayerCounseling' : IDL.Null,
    'consultation' : IDL.Null,
  });
  const AppointmentRequest = IDL.Record({
    'urgencyLevel' : UrgencyLevel,
    'fullName' : IDL.Text,
    'submittedAt' : IDL.Int,
    'submittedBy' : IDL.Opt(IDL.Principal),
    'churchOrOrganization' : IDL.Opt(IDL.Text),
    'preferredDate' : IDL.Int,
    'preferredTime' : IDL.Nat,
    'consentGiven' : IDL.Bool,
    'details' : IDL.Text,
    'emailAddress' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'requestType' : RequestType,
    'leaderRequested' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllRequests' : IDL.Func([], [IDL.Vec(AppointmentRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAppointmentRequest' : IDL.Func([AppointmentRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };